spring.application.name=courseweb

# M\u1eb7c \u0111\u1ecbnh k\u00edch ho\u1ea1t profile 'dev' khi ch\u1ea1y m\u00e1y c\u00e1 nh\u00e2n
spring.profiles.active=dev

# C\u1ed5ng port m\u1eb7c \u0111\u1ecbnh chung c\u1ee7a d\u1ef1 \u00e1n
server.port=8080
