# ========================================
# CẤU HÌNH CÁ NHÂN (SAO CHÉP THÀNH application-dev.properties)
# ========================================

# Database kết nối (SQL SERVER)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=courseweb_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=dien_mat_khau_cua_ban_o_day
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true


